### ISSUE TITLE
0 download, upload through the roof

### ISSUE THREAD

**Issue by kenjibailly** [librespeed/speedtest#408]
I'm not sure if I'm doing something wrong, need to edit some files or not.
My download is always 0 and upload around 400mbps, which is completely wrong.

![image](https://user-images.githubusercontent.com/9883910/109391268-75f27f00-7916-11eb-8b97-8b7f5d7f96d6.png)

https://librespeed.org/ gives me the right results.

I used the docker install like this:
```
  librespeed:
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    restart: unless-stopped
    volumes:
      - /home/ubuntu/docker/librespeed/config:/config
    ports:
      - 8082:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - PASSWORD=password
```

Been trying to check out the configs and wiki, but I'm not getting any further than this.
