### ISSUE TITLE
Always Unknown ISP on standard ISP

### ISSUE THREAD

**Issue by GerdRuetten** [librespeed/speedtest#603]
## Description
I using speedtest as docker compose in the latest version (and testing with dev-branch).
I using the servers.json from your side.
On all ISP i get "Unknown ISP".
Only my own ISP (Deutsche Glasfaser) / Testserver is show me up

## Server
Docker compose with:

```
version: '3.7'
services:
  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    environment:
      MODE: dual
      TITLE: "Speedtest - ruetten.ovh"
      TELEMETRY: "true"
      ENABLE_ID_OBFUSCATION: "false"
      REDACT_IP_ADDRESSES: "false"
      PASSWORD: "password"
      EMAIL: "gerd@ruetten.ovh"
      DISABLE_IPINFO: "false"
      DISTANCE: "km"
      WEBPORT: 8686
    ports:
      - "8686:8686" # webport mapping (host:container)
    volumes:
      - ./data/database:/database
      - ./data/servers.json:/servers.json
```
## Client
Chrome

## Steps to reproduce
You can test it under:
[https://speedtest.ruetten.ovh](https://speedtest.ruetten.ovh)

## Expected behaviour
Resolve the ISP

## Screenshots
<img width="810" alt="image" src="https://github.com/librespeed/speedtest/assets/97361636/c32b65ce-2346-40c1-9080-c3059c69f3e0">

My own ISP/Testserver

<img width="828" alt="image" src="https://github.com/librespeed/speedtest/assets/97361636/823d45ba-4153-42cb-afb7-be932b0db41f">

<img width="1703" alt="image" src="https://github.com/librespeed/speedtest/assets/97361636/c865dd75-58ee-4230-a441-9a62e921839a">
