### ISSUE TITLE
IP reported as null when proxied through Apache

### ISSUE THREAD

**Issue by bobbyl140** [librespeed/speedtest#609]
## Description
I use the Docker container of librespeed from linuxserver.io behind an Apache reverse proxy. When taking a speed test, my client IP always shows as null. I have set the `X-Forwarded-For` header, which works in other applications. I originally asked the linuxserver team about this, and they suggested Apache might be unsupported which isn’t something they control, and that there’s more to the IP check then that one header. 

## Server
Apache: 2.4.57
Podman: 4.6.1
Container: `registry.gitlab.com/linuxserver.io/docker-librespeed/librespeed:latest`

## Client

Safari and Firefox on macOS 14.4, Microsoft Edge and Firefox on Windows 11 21H2, Safari on iOS 17.4.1

## Steps to reproduce
* Do this
* Do that
* Bad stuff happens

## Expected behaviour
What should have happened

## Screenshots
If necessary, add screenshots of the test.
F12 > Network screenshots can be particularly useful

**Comment by bobbyl140** [comment]
Sorry, sent early. About to finish filling out

**Comment by sstidl** [comment]
The image mentioned by you is not made by us so i don't know the difference.
Regarding the unknown ISP issue, you find other issues with the solution here.

**Comment by bobbyl140** [comment]
It’s more than just an unknown ISP, the IP address is showing as null too. They said they couldn’t help me because they didn’t make the software, so I’m not quite sure what else to do.

**Comment by sstidl** [comment]
Have you tried to use our image?

**Comment by bobbyl140** [comment]
I had not actually, I just tried it and the same thing occurs. Here's my `docker-compose.yml`:

```yml
version: '3.7'
services:
  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:dev
    restart: always
    volumes:
      - ./speedtest/db:/database
    environment:
      MODE: standalone
      TELEMETRY: true
      PASSWORD: REDACTED
      EMAIL: admin@example.com
      DISTANCE: mi
    ports:
      - "9065:80"
```
