### ISSUE TITLE
Dual mode is broken

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [librespeed/speedtest#666]
## Description
Whenever I try to use dual mode it does not let me select servers from dropmenu. it only see its local self but not the remote server I added 

## Server
Every info you can provide about your server: web server, database, PHP version, ... as well as server-side speedtest settings
If possible, provide an URL to your speedtest so we can check it

## Client
Brave, Arch Linux 

## Steps to reproduce
* Follow https://github.com/librespeed/speedtest/blob/master/doc_docker.md 
* when using mode: dual it does not show all servers in servers.json file 

## Expected behaviour
in dual mode it sees itself and other server and let me select between servers

## Screenshots
![image](https://github.com/user-attachments/assets/6e0ccec3-ad05-48b1-9181-a5c99816dbbd)
with dual mode

![image](https://github.com/user-attachments/assets/1f782c3b-01a9-498e-bc8c-7475da8c21be)
without dual mode, I run 2 images now one with mode frontend and other with backend locally

## configs
servers.json:
```
[
    {
        "name": "Server 1",
        "server": "//public-ip:port/",
        "dlURL": "garbage.php",
        "ulURL": "empty.php",
        "pingURL": "empty.php",
        "getIpURL": "getIP.php"
    },
    { 
        "name": "Server 2",
        "server": "//public-ip:port/",
        "dlURL": "garbage.php",
        "ulURL": "empty.php",
        "pingURL": "empty.php",
        "getIpURL": "getIP.php"
    }
]
```
docker compose (main server)
```
  librespeed:
    container_name: librespeed
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    volumes:
      - ./librespeed/servers.json:/servers.json
    environment:
      MODE: dual
      #CORS_ALLOW_ORIGIN: "*"
      #TITLE: "LibreSpeed"
      #TELEMETRY: "false"
      #ENABLE_ID_OBFUSCATION: "false"
      #REDACT_IP_ADDRESSES: "false"
      #PASSWORD:
      #EMAIL:
      #DISABLE_IPINFO: "false"
      #IPINFO_APIKEY: "your api key"
      #DISTANCE: "km"
      #WEBPORT: 80
    ports:
      - "8020:80" # webport mapping (host:container)
```
the second server
```
  librespeed:
    container_name: librespeed
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    volumes:
      - ./librespeed/servers.json:/servers.json
    environment:
      MODE: backend
      #MODE: frontend
      #TITLE: "LibreSpeed"
      #TELEMETRY: "false"
      #ENABLE_ID_OBFUSCATION: "false"
      #REDACT_IP_ADDRESSES: "false"
      #PASSWORD:
      #EMAIL:
      #DISABLE_IPINFO: "false"
      #IPINFO_APIKEY: "your api key"
      #DISTANCE: "km"
      #WEBPORT: 80
    ports:
      - "8020:80" # webport mapping (host:container)
```
but when I use both images one for frontend and other for backend it works fine on main server and I can see both servers
