### ISSUE TITLE
Issue with fetching results using docker and mysql - php modules missing from image?

### ISSUE THREAD

**Issue by yurividal** [librespeed/speedtest#684]
Hi. I am trying to implement librespeed on docker, using a local mysql DB.

The tests works, but i can't access the results.

![image](https://github.com/user-attachments/assets/e3c690ef-8c50-4c56-81fe-5b0e7d018c27)

If i login to the database container, i'm able to see the database and the test results.
The problem seems to be on the results page.

Here is the container error log:

````
127.0.0.1 - - [26/Nov/2024:17:45:12 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.62 (Debian) PHP/8.4.1 (internal dummy connection)"
<br />
<b>Warning</b>:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20240924/gd.so (libpng16.so.16: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20240924/gd.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20240924/gd.so.so: cannot open shared object file: No such file or directory)) in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  PHP Startup: Unable to load dynamic library 'pdo_pgsql.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20240924/pdo_pgsql.so (libpq.so.5: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20240924/pdo_pgsql.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20240924/pdo_pgsql.so.so: cannot open shared object file: No such file or directory)) in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  PHP Startup: Unable to load dynamic library 'pgsql.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20240924/pgsql.so (libpq.so.5: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20240924/pgsql.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20240924/pgsql.so.so: cannot open shared object file: No such file or directory)) in <b>Unknown</b> on line <b>0</b><br />
127.0.0.1 - - [26/Nov/2024:17:45:19 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.62 (Debian) PHP/8.4.1 (internal dummy connection)"
<br />
<b>Warning</b>:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20240924/gd.so (libpng16.so.16: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20240924/gd.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20240924/gd.so.so: cannot open shared object file: No such file or directory)) in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  PHP Startup: Unable to load dynamic library 'pdo_pgsql.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20240924/pdo_pgsql.so (libpq.so.5: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20240924/pdo_pgsql.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20240924/pdo_pgsql.so.so: cannot open shared object file: No such file or directory)) in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  PHP Startup: Unable to load dynamic library 'pgsql.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20240924/pgsql.so (libpq.so.5: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20240924/pgsql.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20240924/pgsql.so.so: cannot open shared object file: No such file or directory)) in <b>Unknown</b> on line <b>0</b><br />

````

Here is my docker-compose.yaml file:

````
services:
  librespeed:
    image: ghcr.io/librespeed/speedtest:latest
    container_name: librespeed
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=3306
      - USERNAME=librespeed_user
      - DB_PASSWORD=redacted
      - DB_USERNAME=librespeed_user
      - DB_NAME=librespeed_db
      - ENABLE_DBSTORE=true
      - TELEMETRY=true
      - DB_TYPE=mysql
      - PASSWORD=redacted
      - MODE=standalone
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 80:80

  db:
    image: mysql:8
    container_name: librespeed_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=redacted
      - MYSQL_DATABASE=librespeed_db
      - MYSQL_USER=librespeed_user
      - MYSQL_PASSWORD=redacted
    volumes:
      - .db_data:/var/lib/mysql
    restart: unless-stopped
````
